Map<String, String> diseaseReport = {
  "Corn Cercospora Leaf Spot":
      "Corn Cercospora Leaf Spot is caused by fungi (Cercospora zeae-maydis or C. zeina). Look for rectangular, brown/gray lesions on leaves, especially lower ones. Warm, humid weather and corn residue buildup favor its spread. Here's how to tackle it: Plant resistant corn varieties. Practice crop rotation (avoid planting corn after corn). Tillage helps break down residue where the fungus survives. Apply fungicides as needed, following label instructions. Monitor fields regularly for early signs of infection.",
  "Corn Common Rust":"Cause: Fungal enemy, Puccinia sorghi, loves cool, moist nights. Symptoms: Small yellow flecks turn into brick-red, raised pustules on both leaf surfaces. Impact: Usually harmless to yield, but severe cases can reduce photosynthesis. Solutions: 1. Plant resistant corn varieties. 2. Rotate crops to avoid overwintering spores. 3. Destroy crop residue to eliminate fungal hideouts. 4. Timely fungicide application in severe outbreaks (follow label instructions). Bonus tip: Monitor fields regularly for early signs and act swiftly!",
  "Corn Healthy":"Your crop looks healthy",
  "Corn Northern Leaf Blight":"Cause: Fungus Exserohilum turcicum loves humid climates. Symptoms: Long, tan lesions running parallel to veins, turning gray/green, eventually merging. Lower leaves first, then upwards. Impact: Reduces photosynthesis, stunting growth and potentially harming yield, especially if it hits early. Solutions: 1. Plant resistant corn varieties. 2. Rotate crops to avoid leftover spores in soil. 3. Clean up crop residue after harvest to deny fungus shelter. 4. Timely fungicide application in severe cases (follow label instructions). 5. Monitor fields regularly, especially during humid periods.",
  "Corn Streak":"Cause: Maize streak virus, transmitted by leafhoppers. Symptoms: Yellow or white streaks running parallel on leaves, stunting, reduced cob development. Impact: Significant yield losses, especially in early infections. Solutions:1. Plant resistant corn varieties. 2. Control leafhoppers with insecticides or insect nets. 3. Eradicate grassy weeds that harbor leafhoppers. 4. Early planting can help plants outpace the virus. 5. Monitor fields regularly for early signs and take action.",
  "Pepper Cercospora":"Cause: Fungal foes, Cercospora beticola or C. capsici, thrive in cool, wet weather. Symptoms: Round, brown spots with gray/green centers on leaves, defoliation in severe cases. Impact: Reduced photosynthesis, stunted growth, potential yield loss. Solutions: 1. Plant resistant pepper varieties. 2. Improve air circulation with proper spacing and pruning. 3. Water deeply and less frequently to avoid wet leaves. 4. Remove infected leaves and debris to reduce spore spread. 5. Fungicide application in severe cases (follow label instructions).",
  "Pepper Fusarium":"Cause: Fusarium fungi (F. oxysporum f. sp. capsici) lurk in soil, attacking roots. Symptoms: Wilting, yellowing leaves, stunting, vascular browning in stems. Starts with bottom leaves. Impact: Devastating yield losses, plant death in severe cases. Solutions: 1. Plant resistant pepper varieties. 2. Practice crop rotation to avoid soil-borne spores. 3. Solarize soil before planting to kill pathogens. 4. Improve soil drainage and avoid overwatering. 5. No effective cure, focus on prevention and early detection.",
  "Pepper Healthy":"Your crop looks healthy",
  "Pepper Leaf Blight":"Unfortunately, the term 'Pepper Leaf Blight' can refer to several different diseases affecting pepper plants. To give you the most accurate information, I need to know which specific type of leaf blight you're interested in. Here are some common types of pepper leaf blight: Bacterial Leaf Spot: Caused by bacteria, leading to small, water-soaked lesions on leaves. Phytophthora Blight: Caused by a fungus-like organism, causing stem cankers, fruit rot, and leaf wilting. Early Blight (Alternaria Leaf Spot): Caused by a fungus, showing circular or irregular brown spots on leaves. Late Blight: Caused by a fungus, leading to large, water-soaked lesions and rapid leaf death.",
  "Pepper Leaf Curl":"Cause: Multiple culprits lurk: 1. Pepper leaf curl virus (PepLCV): Transmitted by whiteflies, causing severe stunting, curled leaves, and yield loss. 2. Thrips, aphids, and mites: Sucking pests that damage leaves, causing curling and distortion. 3. Environmental stress: Heat, drought, and nutrient deficiencies can also trigger leaf curl. Symptoms: Upward or downward curling of leaves, stunting, stunted flowers, reduced fruit production. Impact: Depending on cause, severity can range from mild cosmetic issues to devastating yield loss. Solutions: 1. Identify the cause: Observe for pests, check growing conditions, and consider PepLCV presence in your area. 2. Control whiteflies: Insecticidal soap, neem oil, or biological controls like parasitic wasps. 3. Manage thrips, aphids, and mites: Insecticidal soap, predatory mites, or insecticidal oils. 4. Optimize growing conditions: Ensure proper watering, temperature, and nutrient levels. 5. For PepLCV: Plant resistant varieties, remove infected plants, control whiteflies.",
  "Pepper Leaf Mosaic":"Cause: Viruses (AMV, PeMV, CMV) spread by aphids or thrips. Symptoms: Patchy yellow/green leaves, deformed leaves, stunted growth, potential fruit malformation. Impact: Reduced photosynthesis, stunted plants, potential yield loss. Solutions: 1. Identify virus: Consider local prevalence and symptoms. 2. Remove infected plants: Prevent spread. 3. Control aphids/thrips: Insecticidal soap, neem oil, or biological controls. 4. Plant resistant varieties (if available): Reduce risk. 5. Practice good sanitation: Clean tools, remove weeds, avoid contact with infected plants. 6. Start with healthy seedlings: Reduce risk of introducing virus.",
  "Pepper Septoria":"Cause: Fungal foe, Septoria lycopersici, thrives in warm, humid conditions. Symptoms: Small yellow spots on lower leaves, turning brown/gray with dark borders. Spots enlarge and merge, causing leaf loss. Impact: Reduced photosynthesis, stunted growth, potential fruit sunscald if leaves fall excessively. Solutions: 1. Plant resistant pepper varieties. 2. Good air circulation: Space plants properly, prune for airflow. 3. Water deeply and infrequently: Avoid wetting leaves. 4. Remove infected leaves and debris: Reduce spore spread. 5. Fungicide in severe cases (follow label instructions): Early intervention key.",
  "Tomato Early Blight":"Cause: Fungal enemy, Alternaria solani, thrives in warm, humid weather. Symptoms: Look for small, dark brown spots, often with concentric rings, on lower leaves first. Spots enlarge, becoming dry and papery. Can spread to stems and fruits. Impact: Defoliation, reduced fruit quality, and yield loss if severe. Solutions: 1. Plant resistant tomato varieties. 2. Space plants for good air circulation. 3. Water deeply and infrequently, avoiding wet leaves. 4. Remove infected leaves and debris to prevent spore spread. 5. Fungicide application in severe cases (follow label instructions).",
  "Tomato Fusarium":"Cause: Fusarium fungus lurks in soil, attacking roots. Symptoms: Wilting, yellowing, stunting, one-sided progression. Brown vascular tissue in stem. Impact: Devastating wilt and potential plant death. Solutions: 1. Plant resistant varieties. 2. Rotate crops to avoid soilborne spores. 3. Solarize soil before planting. 4. Sanitize tools and mulch with organic matter. 5. No cure, focus on prevention and early detection.",
  "Tomato Healthy":"Your crop looks healthy",
  "Tomato Late Blight":"Cause: Fungal foe, Phytophthora infestans, thrives in cool, wet weather. Symptoms: Watch for water-soaked patches on leaves, turning brown and spreading rapidly. Gray fuzz on leaf undersides in humid conditions. Fruits develop rough, brown lesions. Impact: Devastating, causing rapid plant collapse and fruit rot, leading to significant yield loss. Solutions: 1. Plant resistant tomato varietie. 2. Space plants for good air circulation. 3. Water deeply and infrequently, avoiding wet leaves. 4. Remove and destroy infected leaves and debris. 5. Fungicide application in severe cases (follow label instructions, act early).",
  "Tomato Leaf Curl":"Causes: Heat, drought, overwatering, viruses (TYLCV, ToMV), pests (aphids, whiteflies, thrips). Symptoms: Upward/downward curling, cupping, stunting, discoloration (varies with cause). Impact: Usually cosmetic, but severe cases affect growth/yield. Solutions: 1. Identify cause (observe symptoms, conditions, potential pests). 2. Address stress (adjust watering, fertilize, mulch, shade). 3. For viruses: remove infected plants, control whiteflies (TYLCV vector). 4. For pests: use insecticidal soap, neem oil, or biological controls. 5. Monitor closely and act promptly.",
  "Tomato Mosaic":"Cause: Puzzle of viruses: Tobacco mosaic virus (TMV): Widespread, causing yellow/green mottling, stunting. Tomato mosaic virus (ToMV): Similar symptoms, often with fern-like leaves. Symptoms: Patchy yellow/green areas on leaves, deformed leaves, stunted growth, fruit malformation. Impact: Reduced photosynthesis, stunted plants, potential yield loss. Solutions: 1. Plant resistant varieties. 2. Control aphids and whiteflies (virus vectors): Insecticidal soap, neem oil, or biological controls. 3. Practice good sanitation: Clean tools, remove weeds, avoid contact with infected plants. 4. Start with healthy seedlings: Reduce risk of introducing the virus.",
  "Tomato Septoria":"Cause: Fungal foe, Septoria lycopersici, thrives in warm, humid weather. Symptoms: Look for small, gray centers with brown borders on lower leaves first. Spots enlarge, becoming numerous. Can spread to stems and fruits. Impact: Defoliation, reduced fruit quality, and potential yield loss if severe. Solutions: 1. Plant resistant tomato varieties. 2. Space plants for good air circulation. 3. Water deeply and infrequently, avoiding wet leaves. 4. Remove infected leaves and debris to prevent spore spread. 5. Fungicide in severe cases (follow label instructions, act early).",
};

/// Retrieves the features of a disease based on its name.
///
/// Given a [diseaseName], this method searches for the associated features
/// in the [diseaseReport] map and returns them. If the [diseaseName] is not
/// found in the map, it returns "Not found".
///
/// Parameters:
///   - diseaseName: The name of the disease for which features are to be retrieved.
///
/// Returns:
///   A string representing the features of the disease, or "Not found" if the
///   disease name is not present in the [diseaseReport] map.
String getDiseaseReport(String diseaseName) {
  String? features = diseaseReport[diseaseName];
  return features ?? "Corresponding disease report was not found";
}
